### ISSUE TITLE
editor->getSelText() strips character

### ISSUE THREAD

**Issue by vinsworldcom** [pryrt/Win32-Mechanize-NotepadPlusPlus#87]
Using latest Notepad++ 8.5.3 RC1 and "perlscript" v0.010, the `editor->getSelText()` method seems to strip the last character in the selection.

```
use Win32::Mechanize::NotepadPlusPlus qw/:all/;
print editor->getSelText() . "\n";
```

Open Notepad++, enter "1234" (no newline) in the editor and highlight it all and then run the script; output:

```
PS MVINCENT ~ > .\tmp\nt.pl
123
```

Note that if you enter "1234\n" where `\n` is the "Enter" and highlight everything (including the "newline"), you get expected results:

```
PS MVINCENT ~ > .\tmp\nt.pl
1234
```

Cheers.

**Comment by pryrt** [comment]
That's because since v0.010 was released, Scintilla changed the definition SCI_GETSELTEXT and some of the similar ones (when Scintilla was updated in N++ v8.4).  My work-in-progress [branch for >v8.4.8](https://github.com/pryrt/Win32-Mechanize-NotepadPlusPlus/tree/npp848) should fix that problem: 90e3fa3 should be the fix.

Try the version from that branch; if it doesn't fix it, I'll add a test case and try to debug it.

**Comment by vinsworldcom** [comment]
Wow you're fast!  Yes, that commit does fix it for me.  I notice that's only 2 commits ahead of master and there are a lot more on that branch.  Is that still a work in progress, or should I install the latest commit on that branch?  Happy to stay where I am as it's working now ..

**Comment by pryrt** [comment]
The current branch is passing the existing test suite, so it should be working.  I have been recently starting to bring in the new scintilla messages, but if you don't need any of those, what you have or the latest commit on the branch should be sufficient.
